name: Test Workflow 2
on:
  workflow_dispatch:
jobs:
    job1:
      runs-on: self-hosted
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Job 1
          run: |
            echo "Running job 1..."
            # Add your job commands here
            echo "Job 1 completed successfully."

    job2:
      runs-on: self-hosted
      needs: job1
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Job 2
          run: |
            echo "Running job 2..."
            # Add your job commands here
            echo "Job 2 completed successfully."